"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Loader2, MapPin, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";

export default function VenueManager({ tournamentId }) {
  const [venues,setVenues]=useState([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const [form,setForm]=useState({name:"",shortName:"",address:"",capacity:""});
  const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/tournaments/${tournamentId}/venues`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to load venues");setVenues(b.data||[]);}catch(e){toast.error(e.message);}finally{setLoading(false);}},[tournamentId]);
  useEffect(()=>{load();},[load]);
  async function add(){if(!form.name.trim())return;setSaving(true);try{const r=await fetch(`/api/tournaments/${tournamentId}/venues`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,capacity:form.capacity?Number(form.capacity):null})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to add venue");setForm({name:"",shortName:"",address:"",capacity:""});toast.success("Venue added");await load();}catch(e){toast.error(e.message);}finally{setSaving(false);}}
  async function patch(id,data){const r=await fetch(`/api/tournaments/${tournamentId}/venues/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to update venue");await load();}
  async function remove(id){if(!window.confirm("Delete this unused venue?"))return;try{const r=await fetch(`/api/tournaments/${tournamentId}/venues/${id}`,{method:"DELETE"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Unable to delete venue");toast.success("Venue deleted");await load();}catch(e){toast.error(e.message);}}
  return <div className="page-shell space-y-6"><div className="page-header"><div><Link href={`/dashboard/tournaments/${tournamentId}`} className="mb-3 inline-flex items-center gap-1 text-sm font-semibold text-slate-500 hover:text-slate-950"><ArrowLeft className="h-4 w-4"/>Tournament control</Link><p className="page-eyebrow">Competition setup</p><h1 className="page-title">Venues & grounds</h1><p className="page-description">Create the actual grounds used by this tournament. Fixtures can still retain a display venue name for backward compatibility.</p></div></div><section className="surface-card p-5"><h2 className="font-semibold text-slate-950">Add venue</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Input placeholder="Venue name" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/><Input placeholder="Short name" value={form.shortName} onChange={(e)=>setForm({...form,shortName:e.target.value})}/><Input placeholder="Address / location" value={form.address} onChange={(e)=>setForm({...form,address:e.target.value})}/><Input type="number" min="0" placeholder="Capacity" value={form.capacity} onChange={(e)=>setForm({...form,capacity:e.target.value})}/></div><Button className="mt-4" onClick={add} disabled={saving||!form.name.trim()}>{saving?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<Plus className="mr-2 h-4 w-4"/>}Add venue</Button></section><section className="surface-card overflow-hidden"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-950">Tournament venues</h2></div>{loading?<div className="p-8 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin text-slate-400"/></div>:venues.length?<div className="divide-y divide-slate-100">{venues.map((v)=><div key={v.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 gap-3"><div className="rounded-lg bg-slate-100 p-2"><MapPin className="h-4 w-4 text-slate-600"/></div><div><p className="font-semibold text-slate-950">{v.name}</p><p className="mt-1 text-xs text-slate-500">{v.address||"No address"}{v.capacity?` · Capacity ${v.capacity.toLocaleString("en-IN")}`:""}</p></div></div><div className="flex items-center gap-3"><label className="flex items-center gap-2 text-xs font-semibold text-slate-600"><Switch checked={v.isActive} onCheckedChange={(checked)=>patch(v.id,{isActive:Boolean(checked)}).catch((e)=>toast.error(e.message))}/>Active</label><Button variant="ghost" size="icon" onClick={()=>remove(v.id)}><Trash2 className="h-4 w-4 text-slate-500"/></Button></div></div>)}</div>:<p className="p-8 text-center text-sm text-slate-500">No venues configured yet.</p>}</section></div>;
}
