
import Link from "next/link";
import { CalendarClock, ChevronRight, Shield, Trophy, Users } from "lucide-react";
import MatchBrowser from "@/modules/tournaments/components/public/MatchBrowser";

const label=(v="")=>String(v).replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

function Standings({pools}) {
 if(!pools?.length)return null;
 return <section id="standings" className="rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="font-black text-slate-950">Standings</h2></div><div className="grid xl:grid-cols-2">{pools.map(pool=><div key={pool.pool} className="overflow-x-auto border-b border-slate-100 p-4 xl:border-r"><p className="mb-3 text-xs font-black uppercase tracking-wider text-slate-500">Pool {pool.pool}</p><table className="w-full min-w-[500px] text-sm"><thead><tr className="text-xs text-slate-500"><th className="pb-2 text-left">#</th><th className="pb-2 text-left">Team</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GD</th><th>Pts</th></tr></thead><tbody>{pool.standings.map(row=><tr key={row.familyId} className="border-t border-slate-100"><td className="py-2 font-bold">{row.position}</td><td className="py-2 font-semibold"><Link href={`/teams/${row.familyId}`} className="hover:text-red-700">{row.family}</Link></td><td className="text-center">{row.played}</td><td className="text-center">{row.won}</td><td className="text-center">{row.drawn}</td><td className="text-center">{row.lost}</td><td className="text-center">{row.goalDifference}</td><td className="text-center font-black">{row.points}</td></tr>)}</tbody></table></div>)}</div></section>;
}

export default function EventCenter({event}) {
 return <main className="min-h-screen bg-slate-100 pb-12 pt-[88px]">
  <section className="border-b border-slate-800 bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"><Link href="/tournament" className="text-xs font-bold text-slate-400 hover:text-white">← Tournament centre</Link><div className="mt-4 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-red-400">{event.eventCode||label(event.sportType)} · {label(event.category)}</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">{event.name}</h1><p className="mt-2 text-sm text-slate-400">{event.tournament.shortName||event.tournament.name}{event.format?` · ${event.format}`:""}</p></div><div className="flex gap-5 text-sm text-slate-300"><span><b className="block text-lg text-white">{event.counts.registrations}</b>Teams</span><span><b className="block text-lg text-white">{event.counts.matches}</b>Matches</span></div></div><nav className="mt-5 flex gap-1 overflow-x-auto">{[["#matches","Matches"],["#standings","Standings"],["#teams","Teams"],["#honours","Honours"]].map(([href,name])=><a key={href} href={href} className="whitespace-nowrap rounded-md bg-white/5 px-3 py-2 text-xs font-bold text-slate-300 hover:bg-white/10 hover:text-white">{name}</a>)}</nav></div></section>
  <div className="mx-auto grid max-w-7xl gap-5 px-4 py-6 sm:px-6 lg:grid-cols-[minmax(0,1.5fr)_minmax(300px,.7fr)] lg:px-8">
   <div className="space-y-5"><MatchBrowser matches={event.allMatches} timeZone={event.tournament.timezone}/><Standings pools={event.pools}/></div>
   <aside className="space-y-5">
    <section id="teams" className="rounded-xl border border-slate-200 bg-white"><div className="flex items-center gap-2 border-b border-slate-200 px-4 py-3"><Users className="h-4 w-4 text-slate-500"/><h2 className="font-black text-slate-950">Teams</h2></div><div className="divide-y divide-slate-100">{event.teams.length?event.teams.map(row=><Link key={row.registrationId} href={row.family.href} className="flex items-center gap-3 p-4 hover:bg-slate-50">{row.family.image?<img src={row.family.image} alt="" className="h-9 w-9 rounded-lg object-cover"/>:<div className="grid h-9 w-9 place-items-center rounded-lg bg-slate-100 text-xs font-black">{(row.family.shortName||row.family.familyName).slice(0,2).toUpperCase()}</div>}<div className="min-w-0"><p className="truncate text-sm font-bold text-slate-950">{row.family.familyName}</p><p className="text-xs text-slate-500">{row.pool?`Pool ${row.pool}`:"Pool not assigned"}</p></div><ChevronRight className="ml-auto h-4 w-4 text-slate-300"/></Link>):<p className="p-6 text-sm text-slate-500">No confirmed teams yet.</p>}</div></section>
    {!!event.placements.length&&<section id="honours" className="rounded-xl border border-slate-200 bg-white"><div className="flex items-center gap-2 border-b border-slate-200 px-4 py-3"><Trophy className="h-4 w-4 text-amber-600"/><h2 className="font-black text-slate-950">Honours</h2></div><div className="divide-y divide-slate-100">{event.placements.map(p=><Link key={p.id} href={p.family.href} className="block p-4 hover:bg-slate-50"><p className="text-[10px] font-black uppercase tracking-wider text-amber-700">{label(p.placement)}</p><p className="mt-1 text-sm font-black text-slate-950">{p.family.familyName}</p></Link>)}</div></section>}
    <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2"><Shield className="h-4 w-4 text-slate-500"/><h2 className="font-black text-slate-950">Competition</h2></div><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Format</dt><dd className="font-semibold">{event.format||"Standard"}</dd></div>{event.teamSize&&<div className="flex justify-between"><dt className="text-slate-500">On field</dt><dd className="font-semibold">{event.teamSize}</dd></div>}{event.matchDurationMinutes&&<div className="flex justify-between"><dt className="text-slate-500">Match duration</dt><dd className="font-semibold">{event.matchDurationMinutes} min</dd></div>}</dl></section>
   </aside>
  </div>
 </main>
}
