import Link from "next/link";
import { CalendarDays, ChevronRight, Radio, Trophy, Users } from "lucide-react";

const label = (value = "") => value.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
const formatDate = (value, options = {}) => value ? new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric", ...options }).format(new Date(value)) : "TBA";

export function PublicTournamentHero({ tournament }) {
  if (!tournament) return <section className="bg-slate-950 px-4 pb-14 pt-32 text-white"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-red-400">Official tournament centre</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">Tournament information will appear here when published.</h1></div></section>;
  const live = tournament.liveMatches?.[0];
  return <section className="bg-slate-100 pb-6 pt-[104px] sm:pt-[112px]">
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="border-b border-slate-200 bg-slate-950 px-5 py-4 text-white sm:px-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-slate-400"><span className="text-red-400">{label(tournament.status)}</span><span>•</span><span>{tournament.year}</span></div><h1 className="mt-1 text-2xl font-black tracking-tight sm:text-4xl">{tournament.name}</h1></div><div className="flex gap-2"><Link href="/tournament" className="rounded-lg bg-white px-4 py-2 text-sm font-bold text-slate-950">Tournament centre</Link>{tournament.status === "REGISTRATION" && <Link href="/tournament-registration" className="rounded-lg bg-red-700 px-4 py-2 text-sm font-bold text-white">Register</Link>}</div></div></div>
        <div className="grid lg:grid-cols-[1.35fr_.65fr]">
          <div className="p-5 sm:p-6"><p className="max-w-3xl text-sm leading-6 text-slate-600 sm:text-base">{tournament.description || "Fixtures, live scores, standings, results and tournament information from the official control system."}</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[[CalendarDays,"Dates",`${formatDate(tournament.startDate,{year:undefined})} – ${formatDate(tournament.endDate)}`],[Users,"Families",tournament.counts.families],[Trophy,"Events",tournament.counts.games],[Radio,"Matches",`${tournament.counts.completedMatches}/${tournament.counts.matches}`]].map(([Icon,k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3"><Icon className="h-4 w-4 text-slate-500"/><p className="mt-3 text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">{k}</p><p className="mt-1 text-sm font-black text-slate-950">{v}</p></div>)}</div></div>
          <div className="border-t border-slate-200 bg-slate-50 p-5 lg:border-l lg:border-t-0 sm:p-6">{live ? <><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-red-600"><span className="h-2 w-2 animate-pulse rounded-full bg-red-600"/> Live now</div><Link href={`/tournament/matches/${live.id}`} className="mt-4 block rounded-xl border border-slate-200 bg-white p-4 hover:border-slate-300">{(()=>{const [a,b]=live.participants||[]; return <><p className="text-xs font-semibold text-slate-500">{live.gameName || label(live.sport)} · {label(live.round)}</p><div className="mt-4 grid grid-cols-[1fr_auto_1fr] items-center gap-2"><p className="truncate text-right font-bold">{a?.family||"TBD"}</p><strong className="rounded-lg bg-slate-950 px-3 py-2 text-lg text-white">{a?.score??0}-{b?.score??0}</strong><p className="truncate font-bold">{b?.family||"TBD"}</p></div><p className="mt-4 flex items-center justify-end gap-1 text-xs font-bold text-blue-700">Open match centre <ChevronRight className="h-3.5 w-3.5"/></p></>})()}</Link></> : <><p className="text-xs font-black uppercase tracking-[.14em] text-slate-500">Next fixture</p>{tournament.upcomingMatches?.[0] ? <Link href={`/tournament/matches/${tournament.upcomingMatches[0].id}`} className="mt-4 block font-bold text-slate-950 hover:text-blue-700">{tournament.upcomingMatches[0].name || `${tournament.upcomingMatches[0].participants?.[0]?.family || "TBD"} vs ${tournament.upcomingMatches[0].participants?.[1]?.family || "TBD"}`} →</Link> : <p className="mt-4 text-sm text-slate-500">Fixtures have not been published yet.</p>}</>}</div>
        </div>
      </div>
    </div>
  </section>;
}

export function TournamentAtAGlance({ tournament }) {
  if (!tournament) return null;
  return <section className="bg-slate-100 py-4"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><h2 className="font-black text-slate-950">Competitions</h2><Link href="/tournament" className="text-xs font-bold text-blue-700">View all →</Link></div><div className="grid sm:grid-cols-2 lg:grid-cols-3">{tournament.games.slice(0,6).map((game)=><div key={game.id} className="border-b border-slate-100 p-4 last:border-0 sm:border-r"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-500">{label(game.category)} · {label(game.sportType)}</p><h3 className="mt-1 font-bold text-slate-950">{game.name}</h3><p className="mt-2 text-xs text-slate-500">{game.registrationCount} teams · {game.matchCount} matches</p></div>)}</div></div></div></section>;
}

export function ResultsPreview({ tournament }) {
  if (!tournament?.recentResults?.length) return null;
  return <section className="bg-slate-100 py-4"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><h2 className="font-black text-slate-950">Latest results</h2><Link href="/tournament#results" className="text-xs font-bold text-blue-700">All results →</Link></div><div className="divide-y divide-slate-100">{tournament.recentResults.slice(0,5).map((match)=>{const [a,b]=match.participants||[];return <Link key={match.id} href={`/tournament/matches/${match.id}`} className="grid grid-cols-[minmax(0,1fr)_auto] gap-4 px-4 py-3 hover:bg-slate-50"><div className="min-w-0"><p className="text-[10px] font-semibold uppercase text-slate-500">{match.gameName||label(match.sport)} · {label(match.round)}</p><p className="mt-1 truncate text-sm font-bold text-slate-950">{a?.family||"TBD"} <span className="px-1 text-slate-400">vs</span> {b?.family||"TBD"}</p><p className="mt-1 text-xs font-semibold text-emerald-700">{match.isDraw?"Draw":match.winnerName?`${match.winnerName} won`:label(match.status)}</p></div><div className="self-center rounded-lg bg-slate-950 px-3 py-2 font-black tabular-nums text-white">{a?.score??0}-{b?.score??0}</div></Link>})}</div></div></div></section>;
}

export function ChampionsPreview({ tournament }) {
  const top=(tournament?.placements||[]).filter((p)=>["FIRST","SECOND","THIRD"].includes(p.placement)).slice(0,6); if(!top.length)return null;
  return <section className="bg-slate-100 py-4 pb-12"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="font-black text-slate-950">Honours</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-3">{top.map((p)=><div key={p.id} className="p-4 sm:border-r"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-amber-700">{p.gameName || label(p.sport)} · {label(p.placement)}</p><p className="mt-1 font-black text-slate-950">{p.familyName}</p></div>)}</div></div></div></section>;
}
