
import Link from "next/link";
import { Award, CalendarClock, ShieldCheck, Target, Trophy, UserRound } from "lucide-react";
const label=(v="")=>String(v).replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const dt=(v)=>v?new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v)):"—";
export default function PlayerProfile({player}){
 const s=player.stats;
 return <main className="min-h-screen bg-slate-100 pb-12 pt-[88px]">
  <section className="border-b border-slate-800 bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><Link href={player.family.href} className="text-xs font-bold text-slate-400 hover:text-white">← {player.family.familyName}</Link><div className="mt-4 flex items-center gap-4">{player.photoUrl?<img src={player.photoUrl} alt="" className="h-24 w-24 rounded-2xl object-cover"/>:<div className="grid h-24 w-24 place-items-center rounded-2xl bg-white/10"><UserRound className="h-9 w-9 text-slate-400"/></div>}<div className="min-w-0"><div className="flex items-center gap-2"><p className="text-xs font-bold uppercase tracking-[.15em] text-red-400">Player profile</p>{player.verificationStatus==="VERIFIED"&&<ShieldCheck className="h-4 w-4 text-emerald-400"/>}</div><h1 className="truncate text-3xl font-black sm:text-4xl">{player.displayName||player.playerName}</h1><p className="mt-1 text-sm font-semibold text-slate-400">{player.jerseyNumber!=null?`#${player.jerseyNumber} · `:""}{player.family.familyName}{player.primarySport?` · ${label(player.primarySport)}`:""}</p></div></div></div></section>
  <div className="mx-auto grid max-w-7xl gap-5 px-4 py-6 sm:px-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(300px,.7fr)] lg:px-8">
   <div className="space-y-5">
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Goals",s.goals,Trophy],["Shots on target",s.shotsOnTarget,Target],["Tracked matches",s.matchesWithRecordedEvents,CalendarClock],["POTM awards",s.playerOfMatchAwards,Award]].map(([k,v,Icon])=><div key={k} className="rounded-xl border border-slate-200 bg-white p-4"><Icon className="h-4 w-4 text-slate-400"/><p className="mt-3 text-2xl font-black tabular-nums text-slate-950">{v}</p><p className="text-xs font-semibold text-slate-500">{k}</p></div>)}</section>
    {player.biography&&<section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-950">Profile</h2><p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-600">{player.biography}</p></section>}
    <section className="rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="font-black text-slate-950">Official event activity</h2><p className="text-xs text-slate-500">Latest recorded goals, shots and disciplinary events.</p></div><div className="divide-y divide-slate-100">{player.recentEvents.length?player.recentEvents.map(e=><Link key={e.id} href={`/tournament/matches/${e.match.id}`} className="grid grid-cols-[46px_minmax(0,1fr)_auto] gap-3 px-4 py-3 hover:bg-slate-50"><span className="text-xs font-black text-slate-400">{e.minute!=null?`${e.minute}′`:"—"}</span><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-950">{label(e.type)}</p><p className="truncate text-xs text-slate-500">{e.match.game?.shortName||e.match.game?.name||"Event"} · {e.match.tournament?.shortName||e.match.tournament?.name}</p></div><span className="text-xs text-slate-400">{dt(e.match.scheduledOn)}</span></Link>):<p className="p-6 text-sm text-slate-500">No player-level events recorded yet.</p>}</div></section>
   </div>
   <aside className="space-y-5">
    <Link href={player.family.href} className="block rounded-xl border border-slate-200 bg-white p-4 hover:border-slate-300"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Family / team</p><div className="mt-3 flex items-center gap-3">{player.family.image?<img src={player.family.image} alt="" className="h-11 w-11 rounded-lg object-cover"/>:<div className="grid h-11 w-11 place-items-center rounded-lg bg-slate-100 font-black">{player.family.familyName.slice(0,2).toUpperCase()}</div>}<p className="font-black text-slate-950">{player.family.familyName}</p></div></Link>
    <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="font-black text-slate-950">Player info</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Sport</dt><dd className="font-semibold">{label(player.primarySport||"—")}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Cards</dt><dd className="font-semibold">{s.greenCards}G · {s.yellowCards}Y · {s.redCards}R</dd></div></dl></section>
    {!!player.achievements?.length&&<section className="rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-4 py-3"><h2 className="font-black text-slate-950">Achievements</h2></div><div className="divide-y divide-slate-100">{player.achievements.map((a,i)=><div key={`${a.title}-${i}`} className="p-4"><p className="text-sm font-bold text-slate-950">{a.title}</p><p className="text-xs text-slate-500">{a.year||""}{a.description?` · ${a.description}`:""}</p></div>)}</div></section>}
   </aside>
  </div>
 </main>
}
