
import Link from "next/link";
import { Search, ShieldCheck, UserRound } from "lucide-react";
const label=(v="")=>String(v).replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function PlayerDirectory({players}) {
 return <main className="min-h-screen bg-slate-100 pb-12 pt-[88px]">
  <section className="border-b border-slate-800 bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.15em] text-red-400">Tournament directory</p><div className="mt-1 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-black sm:text-4xl">Players</h1><p className="mt-2 text-sm text-slate-400">Official public player profiles from active tournament families.</p></div><div className="flex gap-2"><Link href="/teams" className="rounded-lg border border-white/15 px-3 py-2 text-sm font-bold text-slate-200 hover:bg-white/10">Teams</Link><Link href="/search" className="inline-flex items-center gap-2 rounded-lg border border-white/15 px-3 py-2 text-sm font-bold text-slate-200 hover:bg-white/10"><Search className="h-4 w-4"/>Search</Link></div></div></div></section>
  <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">{players?.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{players.map(player=><Link key={player.id} href={player.href} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 hover:border-slate-300 hover:shadow-sm">{player.photoUrl?<img src={player.photoUrl} alt="" className="h-12 w-12 rounded-full object-cover"/>:<div className="grid h-12 w-12 place-items-center rounded-full bg-slate-100"><UserRound className="h-5 w-5 text-slate-400"/></div>}<div className="min-w-0"><div className="flex items-center gap-1.5"><p className="truncate text-sm font-black text-slate-950">{player.displayName||player.playerName}</p>{player.verificationStatus==="VERIFIED"&&<ShieldCheck className="h-3.5 w-3.5 shrink-0 text-emerald-600"/>}</div><p className="truncate text-xs text-slate-500">{player.family.familyName}{player.jerseyNumber!=null?` · #${player.jerseyNumber}`:""}</p>{player.primarySport&&<p className="mt-0.5 text-[10px] font-bold uppercase tracking-wider text-slate-400">{label(player.primarySport)}</p>}</div></Link>)}</div>:<div className="rounded-xl border border-slate-200 bg-white p-10 text-center"><UserRound className="mx-auto h-8 w-8 text-slate-400"/><p className="mt-3 font-bold text-slate-900">No public players available yet.</p></div>}</div>
 </main>
}
