
import Link from "next/link";
import { CalendarClock, Medal, ShieldCheck, Trophy, UserRound, Users } from "lucide-react";

const label=(v="")=>String(v).replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const date=(v)=>v?new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v)):"TBA";
function Result({match,familyId}){const [a,b]=match.participants||[];const mine=a?.familyId===familyId?a:b;const other=a?.familyId===familyId?b:a;const result=match.isDraw||mine?.score===other?.score?"D":match.winnerId===familyId||(!match.winnerId&&mine?.score>other?.score)?"W":"L";return <Link href={`/tournament/matches/${match.id}`} className="grid grid-cols-[32px_minmax(0,1fr)_auto] items-center gap-3 px-4 py-3 hover:bg-slate-50"><span className={`grid h-7 w-7 place-items-center rounded-full text-[10px] font-black ${result==="W"?"bg-emerald-100 text-emerald-700":result==="D"?"bg-amber-100 text-amber-700":"bg-red-100 text-red-700"}`}>{result}</span><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-950">{mine?.family||"Team"} vs {other?.family||"TBD"}</p><p className="truncate text-xs text-slate-500">{match.game?.shortName||match.game?.name||"Event"} · {date(match.scheduledOn)}</p></div><span className="font-black tabular-nums">{mine?.score??0}-{other?.score??0}</span></Link>}

export default function TeamProfile({team}){
  return <main className="min-h-screen bg-slate-100 pb-12 pt-[88px]">
    <section className="border-b border-slate-800 bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8"><Link href="/teams" className="text-xs font-bold text-slate-400 hover:text-white">← All teams</Link><div className="mt-4 flex items-center gap-4">{team.image?<img src={team.image} alt="" className="h-20 w-20 rounded-2xl object-cover"/>:<div className="grid h-20 w-20 place-items-center rounded-2xl bg-white/10 text-2xl font-black">{(team.shortName||team.familyName).slice(0,2).toUpperCase()}</div>}<div className="min-w-0"><p className="text-xs font-bold uppercase tracking-[.15em] text-red-400">Family profile</p><h1 className="truncate text-3xl font-black sm:text-4xl">{team.familyName}</h1>{team.shortName&&<p className="mt-1 text-sm font-semibold text-slate-400">{team.shortName}</p>}</div></div></div></section>
    <div className="mx-auto grid max-w-7xl gap-5 px-4 py-6 sm:px-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(300px,.7fr)] lg:px-8">
      <div className="space-y-5">
        <section className="grid grid-cols-3 gap-3 sm:grid-cols-6">{[["P",team.stats.played],["W",team.stats.won],["D",team.stats.drawn],["L",team.stats.lost],["GF",team.stats.goalsFor],["GD",team.stats.goalDifference]].map(([k,v])=><div key={k} className="rounded-xl border border-slate-200 bg-white p-3 text-center"><p className="text-xl font-black tabular-nums text-slate-950">{v}</p><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{k}</p></div>)}</section>
        {team.description&&<section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-950">About</h2><p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-600">{team.description}</p></section>}
        <section className="rounded-xl border border-slate-200 bg-white"><div className="flex items-center gap-2 border-b border-slate-200 px-4 py-3"><Users className="h-4 w-4 text-slate-500"/><h2 className="font-black text-slate-950">Current players</h2></div><div className="grid sm:grid-cols-2">{team.players.length?team.players.map(p=><Link key={p.id} href={p.href} className="flex items-center gap-3 border-b border-slate-100 p-4 hover:bg-slate-50 sm:border-r">{p.photoUrl?<img src={p.photoUrl} alt="" className="h-10 w-10 rounded-full object-cover"/>:<div className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><UserRound className="h-4 w-4 text-slate-400"/></div>}<div className="min-w-0"><p className="truncate text-sm font-bold text-slate-950">{p.displayName||p.playerName}</p><p className="text-xs text-slate-500">{p.jerseyNumber!=null?`#${p.jerseyNumber} · `:""}{label(p.primarySport||"Player")}</p></div>{p.verificationStatus==="VERIFIED"&&<ShieldCheck className="ml-auto h-4 w-4 text-emerald-600"/>}</Link>):<p className="p-6 text-sm text-slate-500">No active public players.</p>}</div></section>
        <section className="rounded-xl border border-slate-200 bg-white"><div className="flex items-center gap-2 border-b border-slate-200 px-4 py-3"><CalendarClock className="h-4 w-4 text-slate-500"/><h2 className="font-black text-slate-950">Recent matches</h2></div><div className="divide-y divide-slate-100">{team.recentMatches.length?team.recentMatches.map(m=><Result key={m.id} match={m} familyId={team.id}/>):<p className="p-6 text-sm text-slate-500">No published matches yet.</p>}</div></section>
      </div>
      <aside className="space-y-5">
        {!!team.placements.length&&<section className="rounded-xl border border-slate-200 bg-white"><div className="flex items-center gap-2 border-b border-slate-200 px-4 py-3"><Trophy className="h-4 w-4 text-amber-600"/><h2 className="font-black text-slate-950">Tournament honours</h2></div><div className="divide-y divide-slate-100">{team.placements.map(p=><div key={p.id} className="p-4"><p className="text-xs font-bold uppercase tracking-wider text-amber-700">{label(p.placement)}</p><p className="mt-1 text-sm font-bold text-slate-950">{p.game?.shortName||p.game?.name||label(p.sport)}</p><p className="text-xs text-slate-500">{p.tournament?.shortName||p.tournament?.name} · {p.tournament?.year}</p></div>)}</div></section>}
        {!!team.participations.length&&<section className="rounded-xl border border-slate-200 bg-white"><div className="flex items-center gap-2 border-b border-slate-200 px-4 py-3"><Medal className="h-4 w-4 text-slate-500"/><h2 className="font-black text-slate-950">Tournament history</h2></div><div className="divide-y divide-slate-100">{team.participations.slice(0,8).map(p=><div key={p.id} className="p-4"><p className="text-sm font-bold text-slate-950">{p.tournament.shortName||p.tournament.name}</p><p className="mt-1 text-xs text-slate-500">{p.tournament.year} · {p.gameRegistrations.length} event{p.gameRegistrations.length===1?"":"s"}</p></div>)}</div></section>}
      </aside>
    </div>
  </main>
}
